name: data
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denolib/setup-deno@v2
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://www.data.gouv.fr/fr/datasets/r/f868cca6-8da1-4369-a78d-47463f19a9a3
          downloaded_filename: datasets.csv
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://www.data.gouv.fr/fr/datasets/r/b7bbfedc-2448-4135-a6c7-104548d396e7
          downloaded_filename: organizations.csv
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://www.data.gouv.fr/fr/datasets/r/4babf5f2-6a9c-45b5-9144-ca5eae6a7a6d
          downloaded_filename: resources.csv
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://www.data.gouv.fr/fr/datasets/r/d77705e1-4ecd-461c-8c24-662d47c4c2f9
          downloaded_filename: discussions.csv
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://www.data.gouv.fr/fr/datasets/r/970aafa0-3778-4d8b-b9d1-de937525e379
          downloaded_filename: reuses.csv
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://www.data.gouv.fr/fr/datasets/r/1ac234c7-1da4-49cf-a122-646b21d64b43
          downloaded_filename: tags.csv
